using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Gives the Lao house a little surface texture in Module 3 only.
///
/// The house model is flat colour: every face samples one swatch of a palette texture, so it read as
/// smooth plastic. Its prefab and materials are shared with Modules 1 and 2, so rather than change
/// them, the houses this module builds get the same materials switched to a shader that multiplies a
/// world-space grain into the palette colour (Shaders/M3HouseLit.shader). The replacements are
/// generated by Module3HouseSurfaceAssets and live in Resources so a build always carries them.
/// </summary>
public static class M3HouseSurface
{
    /// <summary>House material name -> the Resources asset that replaces it.</summary>
    private static readonly Dictionary<string, string> Replacements = new Dictionary<string, string>
    {
        { "M_Gradient_Light", "Module3/M_M3_House_Light" },   // walls and roof
        { "M_Gradient", "Module3/M_M3_House_Door" },          // door leaves
    };

    private static Dictionary<string, Material> loaded;

    /// <summary>
    /// Textures the house in each of <paramref name="plots"/>. A plot also holds the bed, the villagers and
    /// the yard container, which must keep their own materials, so this picks out the child that is the
    /// house: the one with a "Roof" part.
    /// </summary>
    public static void ApplyToPlots(IReadOnlyList<HouseholdView> plots)
    {
        foreach (var plot in plots)
        {
            foreach (Transform child in plot.transform)
            {
                if (child.Find("Roof") != null) Apply(child.gameObject);
            }
        }
    }

    /// <summary>Swaps the palette materials on <paramref name="house"/> for their textured versions.</summary>
    public static void Apply(GameObject house)
    {
        if (loaded == null)
        {
            loaded = new Dictionary<string, Material>();
            foreach (var pair in Replacements)
            {
                var material = Resources.Load<Material>(pair.Value);
                if (material == null) Debug.LogWarning($"Module 3: '{pair.Value}' is missing, so {pair.Key} stays smooth. "
                                                       + "Run AEDES > Module 3 > Generate House Surface Assets.");
                else loaded[pair.Key] = material;
            }
        }

        foreach (var renderer in house.GetComponentsInChildren<Renderer>(true))
        {
            var materials = renderer.sharedMaterials;
            bool changed = false;
            for (int i = 0; i < materials.Length; i++)
            {
                if (materials[i] != null && loaded.TryGetValue(materials[i].name, out var textured))
                {
                    materials[i] = textured;
                    changed = true;
                }
            }
            if (changed) renderer.sharedMaterials = materials;
        }
    }
}
